
.PHONY: clean

TESTS=pseudo1 tokenizer3 tokenizer2 tokenizer1a tokenizer1 infiles1 block1 cpu1 context1 operation1 arith1 arith2 arith3 cmdline1 parser1 

SRCDIR=../src

SUBDIRS=util

OBJFILES=log.o linked_list.o array_list.o mem.o hashmap.o tokenizer.o infiles.o block.o cpu.o context.o errors.o segment.o operation.o parser.o arith.o print.o inline_list.o parser-config.o cmdline.o pseudo.o

include Makefile.inc

