
.PHONY: clean

TESTS=arith5 arith4 tokenizer3 tokenizer2 tokenizer1a tokenizer1 infiles1 block1 cpu1 context1 operation1 arith1 arith2 arith3 cmdline1 
TESTS+=parser1 pseudo1 parser2 segment1 err1 cmdline2 parser3 print1 arith5 arith6 print2

TESTROOT=..

SUBDIRS=

OBJFILES=log.o linked_list.o array_list.o mem.o hashmap.o tokenizer.o infiles.o block.o cpu.o context.o err.o segment.o operation.o parser.o arith.o print.o inline_list.o parser-config.o cmdline.o pseudo.o print-config.o print-formatted.o

include ../Makefile.inc

