
.PHONY: clean

TESTS=expr5 expr4 tokenizer3 tokenizer2 tokenizer1a tokenizer1 infiles1 block1 cpu1 context1 operation1 expr1 expr2 expr3 cmdline1 
TESTS+=parser1 pseudo1 parser2 segment1 err1 cmdline2 parser3 print1 expr5 expr6 print2 eval1

TESTROOT=..

SUBDIRS=

OBJFILES=log.o linked_list.o array_list.o mem.o hashmap.o tokenizer.o infiles.o block.o cpu.o context.o err.o segment.o instruction.o parser.o expr-parse.o print.o inline_list.o parser-config.o cmdline.o pseudo.o print-config.o print-formatted.o expr-eval.o

include ../Makefile.inc

